name: checker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dio: 4.0.6
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sensors_plus: ^3.0.0
  noise_meter: ^3.2.0
  camera: ^0.10.5
  google_ml_kit: ^0.14.0
  flutter_vision: ^1.1.1
  get: ^4.6.5
  background_fetch: ^1.1.6
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.18.6
  device_info_plus: ^9.0.0
  flutter_background_service_android: ^3.0.3
  flutter_background_service: ^2.4.6
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^14.0.0+2
  is_lock_screen: ^2.0.0
  call_log: ^4.0.0
  workmanager: ^0.5.1
  flutter_isolate: ^2.0.4
  flutter_downloader: ^1.10.3
  path_provider: ^2.0.15
  image_picker: ^0.8.7+5
  google_mlkit_commons: ^0.3.0
  google_mlkit_face_detection: ^0.6.0
  microphone: ^0.1.0
  mic_stream: ^0.6.5
  flutter_sound: ^9.2.13
  flutter_typeahead: ^4.4.0
  firebase_core: ^2.13.0

dependency_overrides:
  audio_streamer:
    path: packages/audio_streamer/
  flutter_background_service_android: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg

